// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhwzytkmulmhtqazjyiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZod3p5dGttdWxtaHRxYXpqeWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4MDU5MTAsImV4cCI6MjA1MjM4MTkxMH0.xN4wexmUsTVzJQbPpxqJ1OMwr8J-B0kP11uIaPOD3-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);